version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create_database.sql
    command: tail -f /dev/null